[colors.bright]
black = "#b0bec4"
blue = "#80d7fe"
cyan = "#a7fdeb"
green = "#b9f6c9"
magenta = "#ff80ab"
red = "#ff8980"
white = "#fefefe"
yellow = "#ffe47e"

[colors.cursor]
cursor = "#edeeed"
text = "#000000"

[colors.normal]
black = "#546d79"
blue = "#40c4fe"
cyan = "#64fcda"
green = "#69f0ad"
magenta = "#ff3f80"
red = "#ff5151"
white = "#fefefe"
yellow = "#ffd73f"

[colors.primary]
background = "#263137"
foreground = "#eceef0"

[colors.selection]
background = "#607c8b"
text = "#eceef0"

[env]
term = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[keyboard]
bindings = [
{ key = "F", mods = "Command|Shift", action = "ToggleFullscreen" },
]

[scrolling]
history = 12000

[window]
decorations = "none"
opacity = 1.0
